name: Node CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build, and test
      run: |
        npm ci
        npm run build --if-present
        npm test
      env:
        CI: true
    - name: Generate Code Coverage Report
      run: |
        istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov     
    - name: Codecov upload
      id: codecov
      uses: codecov/codecov-action@v1.0.5
      with:
          token: ${{ secrets.CODECOV_TOKEN }} #required
          file: ./coverage.xml #optional
          flags: pnp-tests #optional
          name: codecov-ambianic-pnp #optional
          # yml: ./codecov.yml #optional
          fail_ci_if_error: true #optional (default = false) 
    - name: Semantic Release
      uses: codfish/semantic-release-action@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
